Pages/Admin/ActivityLog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Admin
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class ActivityLogModel : PageModel
    {
        private ICosmosDBRepository<ActivityLogItem> _activityLog;
        public IEnumerable<ActivityLogItem> Activities { get; private set; }

        public ActivityLogModel(ICosmosDBRepository<ActivityLogItem> activityLog)
        {
            _activityLog = activityLog; 
        }
        public async Task OnGetAsync()
        {
            Activities = (await _activityLog.GetPagedDocumentsDescending(d => true, a => a.TimeStamp, 150, null)).Result;
        }
        public async Task OnGetNoRobotsAsync()
        {
            Activities = (await _activityLog.GetPagedDocumentsDescending(d => !d.ClientInfo.Contains("bot") && !d.ClientInfo.Contains("Bot") && !d.ClientInfo.Contains("crawler") && !d.ClientInfo.Contains("Crawler"), a => a.TimeStamp, 150, null)).Result;
        }
    }
}

Pages/Admin/Captcha.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using reCAPTCHA.AspNetCore;

namespace robert_brands_com.Pages.Admin
{
    public class CaptchaModel : PageModel
    {
        private IRecaptchaService _recaptcha;

        public CaptchaModel(IRecaptchaService recaptcha)
        {
            _recaptcha = recaptcha;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            RecaptchaResponse captchaValid = await _recaptcha.Validate(Request, false);
            if (!captchaValid.success)
            {
                ModelState.AddModelError("reCaptcha", "Bitte das reCaptcha bestätigen.");
            }
            if (ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
        }
    }
}

Pages/Admin/Environment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


namespace robert_brands_com.Pages.Admin
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class EnvironmentModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Admin/Headers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using System.Security.Claims;

namespace robert_brands_com.Pages.Admin
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class HeadersModel : PageModel
    {
        [BindProperty]
        public IConfiguration Configuration { get; set; }
        public HeadersModel(IConfiguration configuration)
        {
            Configuration = configuration;

        }
        public void OnGet()
        {

        }
    }
}

Pages/Admin/Kategorien.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Admin
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class KategorienModel : PageModel
    {
        private ICosmosDBRepository<ListCategory> repository;
        public IEnumerable<ListCategory> CategoryList { get; private set; }
        public KategorienModel(ICosmosDBRepository<ListCategory> repository)
        {
            this.repository = repository;
        }
        public async Task OnGetAsync()
        {
            CategoryList = await repository.GetDocuments();
        }
        public async Task<IActionResult> OnGetDeleteAsync(string documentid)
        {
            await repository.DeleteDocumentAsync(documentid);
            ViewData["Message"] = "Eintrag gelöscht";

            return RedirectToPage();
        }
    }
}

Pages/Admin/NewCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;

namespace robert_brands_com.Pages.Admin
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class NewCategoryModel : PageModel
    {
        private ICosmosDBRepository<ListCategory> repository;
        [BindProperty]
        public ListCategory Category { get; set; }

        public NewCategoryModel(ICosmosDBRepository<ListCategory> repository)
        {
            this.repository = repository;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnGetChangeCategoryAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            Category = await repository.GetDocument(documentid);
            if (null == Category)
            {
                return new NotFoundResult();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                IEnumerable<ListCategory> list = await repository.GetDocuments(s => s.ListName == Category.ListName && s.Category == Category.Category);
                ListCategory existingOne = list.FirstOrDefault();
                if (null != existingOne)
                {
                    Category.Id = existingOne.Id;
                }
                await repository.UpsertDocument(Category);
                ViewData["Message"] = "Kategorie gespeichert.";
                return RedirectToPage("Kategorien");
            }
            else
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
        }
    }
}

Pages/Admin/ActivityLog.cshtml
@page
@model robert_brands_com.Pages.Admin.ActivityLogModel
@using robert_brands_com.Models;
@{
    ViewData["Title"] = "ActivityLog";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
            <ul class="list-inline">
                <li class="list-inline-item"><a asp-page-handler="get">Alle</a></li>
                <li class="list-inline-item"><a asp-page-handler="norobots">Ohne Robots</a></li>
            </ul>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="bg-light">
                        <tr>
                            <th>Timestamp</th>
                            <th>User</th>
                            <th>Category</th>
                            <th>MessageTag</th>
                            <th>Message</th>
                            <th>ClientInfo</th>
                        </tr>
                    </thead>
                    <tbody class="font-weight-light">
                        @foreach (ActivityLogItem activity in Model.Activities)
                        {
                            <tr>
                                <td>@activity.TimeStamp.ToString("yyyy-MM-dd HH:mm")</td>
                                <td>@activity.User</td>
                                <td>@activity.Category</td>
                                <td>@activity.MessageTag</td>
                                <td>@activity.Message</td>
                                <td class="small">@activity.ClientInfo</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Pages/Admin/Captcha.cshtml
@page
@model robert_brands_com.Pages.Admin.CaptchaModel
@using Microsoft.Extensions.Options
@using reCAPTCHA.AspNetCore
@inject IOptions<RecaptchaSettings> RecaptchaSettings
@{
    ViewData["Title"] = "Captcha";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </div>
        <div class="card-body">
            <form method="post">
                <div asp-validation-summary="All" class="bg-warning"></div>
                <div class="g-recaptcha" data-sitekey="@RecaptchaSettings.Value.SiteKey"></div>
                <button class="btn btn-primary" type="submit">Speichern</button>
                <button type="button" class="btn btn-secondary" onclick="window.history.back()">Abbrechen</button>
            </form>
        </div>
    </div>
</div>

@section HeaderScripts {
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
}

Pages/Admin/Environment.cshtml
@page
@model robert_brands_com.Pages.Admin.EnvironmentModel
@{
    ViewData["Title"] = "Claims";
}
@using System.Security.Claims

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="bg-light">
                        <tr>
                            <th>Claim Type</th>
                            <th>Claim Value</th>
                            <th>Claim Issuer</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Claim claim in User.Claims)
                        {
                            <tr>
                                <td>@claim.Type</td>
                                <td>@claim.Value</td>
                                <td>@claim.Issuer</td>
                            </tr>
                        }
                        <tr>
                            <td>User</td>
                            <td>@User.Identity.Name</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Pages/Admin/Headers.cshtml
@page
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment hostingEnv
@using Microsoft.Extensions.Configuration;
@model robert_brands_com.Pages.Admin.HeadersModel
@{
    ViewData["Title"] = "Headers and Config";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="bg-light">
                        <tr>
                            <th>Header</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (string header in Request.Headers.Keys)
                        {
                            <tr>
                                <td>@header</td>
                                <td>@Request.Headers[header]</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="table-responsive">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead class="bg-light">
                        <tr>
                            <th>Config</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>ASPNETCORE_ENVIRONMENT</td>
                            <td>
                                @hostingEnv.EnvironmentName
                            </td>

                        </tr>
                        @foreach (IConfigurationSection configSection in Model.Configuration.GetChildren())
                        {
                            <tr>
                                <td>@configSection.Key</td>
                                <td>
                                    @configSection.Value
                                    <table>
                                        @foreach (IConfigurationSection subSection in configSection.GetChildren())
                                        {
                                            <tr>
                                                <td> @subSection.Key</td>
                                                <td>: </td>
                                                <td>@subSection.Value</td>
                                            </tr>
                                        }
                                    </table>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Pages/Admin/Kategorien.cshtml
@page
@model robert_brands_com.Pages.Admin.KategorienModel
@using robert_brands_com.Models
@{
    ViewData["Title"] = "Kategorien";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Aktionen</th>
                        <th>Liste</th>
                        <th>Kategorie</th>
                        <th>Anzeigetext</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ListCategory c in Model.CategoryList)
                    {
                        <tr>
                            <td>
                                <a class="btn btn-outline-dark" asp-page="NewCategory" asp-page-handler="changecategory" asp-route-documentid="@c.Id">Ändern</a>
                                <a class="btn btn-outline-dark" asp-page-handler="delete" asp-route-documentid="@c.Id">Löschen</a>
                            </td>
                            <td>@c.ListName</td>
                            <td>@c.Category</td>
                            <td>@c.CategoryDisplay</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div>
            <a class="btn btn-primary" asp-page="NewCategory">Neue Kategorie</a>
        </div>
    </div>
</div>

Pages/Admin/NewCategory.cshtml
@page
@model robert_brands_com.Pages.Admin.NewCategoryModel
@{
    ViewData["Title"] = "Kategorie";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h4>@ViewData["Message"]</h4>
        </div>
        <div class="card-body">
            <form method="post">
                <div asp-validation-summary="All" class="bg-warning"></div>
                <div class="form-group">
                    <label asp-for="Category.ListName">Liste:</label>
                    <input class="form-control" asp-for="Category.ListName" />
                </div>
                <div class="form-group">
                    <label asp-for="Category.Category">Kategorie:</label>
                    <input class="form-control" asp-for="Category.Category" />
                </div>
                <div class="form-group">
                    <label asp-for="Category.CategoryDisplay">Anzeigetext:</label>
                    <input class="form-control" asp-for="Category.CategoryDisplay" />
                </div>
                <button class="btn btn-primary" type="submit">Speichern</button>
                <button type="button" class="btn btn-secondary" onclick="window.history.back()">Abbrechen</button>
            </form>
        </div>
    </div>
</div>