Pages/Fotos/Album.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Fotos
{
    [Authorize(Roles = KnownRoles.AllRolesList)]
    public class AlbumModel : PageModel
    {
        [BindProperty]
        public string Search { get; set; }

        private ICosmosDBRepository<CommentedLinkItem> repository;
        private IActivityLog activityLog;
        public IEnumerable<CommentedLinkItem> CommentedLinks { get; private set; }
        public AlbumModel(ICosmosDBRepository<CommentedLinkItem> repositoryService, IActivityLog activityLogRepository)
        {
            this.repository = repositoryService;
            this.activityLog = activityLogRepository;
        }

        public async Task OnGet(string category = null)
        {
            if (String.IsNullOrEmpty(category))
            {
                IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments();
                CommentedLinks = documents.OrderByDescending(d => d.Date);
            }
            else
            {
                IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments(d => d.Category == category);
                CommentedLinks = documents.OrderByDescending(d => d.Date);
            }
        }
        public async Task<IActionResult> OnGetSearchAsync(string searchExpression)
        {
            if (String.IsNullOrEmpty(searchExpression))
            {
                return new NotFoundResult();
            }
            IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments(d => d.Title.IndexOf(searchExpression, StringComparison.OrdinalIgnoreCase) >= 0 ||
                                                                                          d.Description.IndexOf(searchExpression, StringComparison.OrdinalIgnoreCase) >= 0 ||
                                                                                          d.Category.IndexOf(searchExpression, StringComparison.OrdinalIgnoreCase) >= 0 ||
                                                                                          d.ListName.IndexOf(searchExpression, StringComparison.OrdinalIgnoreCase) >= 0);
            CommentedLinks = documents.OrderByDescending(d => d.Date);
            return Page();
        }
        // only on page level [Authorize(KnownRoles.Admin)]
        public async Task<IActionResult> OnGetDeleteLinkAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            await repository.DeleteDocumentAsync(documentid);
            ViewData["Message"] = "Eintrag gelöscht";

            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostSearchAsync()
        {
            if (String.IsNullOrEmpty(Search))
            {
                return RedirectToPage();
            }
            string searchLowercase = Search.ToLower();
            IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments(d => d.Title.ToLower().Contains(searchLowercase) ||
                                                                                     d.Description.ToLower().Contains(searchLowercase) ||
                                                                                     d.Category.ToLower().Contains(searchLowercase) ||
                                                                                     d.ListName.ToLower().Contains(searchLowercase));
            CommentedLinks = documents.OrderByDescending(d => d.Date);
            return Page();
        }
    }
}

Pages/Fotos/EditContentItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Fotos
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class EditContentItemModel : PageModel
    {
        private ICosmosDBRepository<CommentedLinkItem> _repository;
        [BindProperty]
        public string CommentedLinkItemId { get; set; }
        [BindProperty]
        public ContentItem PhotoPageDetail { get; set; }

        public EditContentItemModel(ICosmosDBRepository<CommentedLinkItem> repository)
        {
            _repository = repository;
        }
        public async Task<IActionResult> OnGetAsync(string documentid, string contentitemid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            CommentedLinkItemId = documentid;
            CommentedLinkItem linkItem = await _repository.GetDocument(documentid);
            if (null == linkItem)
            {
                return new NotFoundResult();
            }
            List<ContentItem> contentItems = (linkItem.Infos != null) ? new List<ContentItem>(linkItem.Infos) : new List<ContentItem>();
            if (String.IsNullOrEmpty(contentitemid))
            {
                PhotoPageDetail = new ContentItem { ContentType = ContentType.Text, UniqueId = Guid.NewGuid().ToString(), SortOrder = 10 };
                if (contentItems.Count > 0)
                {
                    PhotoPageDetail.SortOrder = contentItems.Last().SortOrder + 10;
                }
            }
            else
            {
                if (null == linkItem.Infos)
                {
                    return new NotFoundResult();
                }
                PhotoPageDetail = contentItems.Find(c => c.UniqueId == contentitemid);
                if (null == PhotoPageDetail)
                {
                    return new NotFoundResult();
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                CommentedLinkItem linkItem = await _repository.GetDocument(CommentedLinkItemId);
                if (null == linkItem)
                {
                    return new NotFoundResult();
                }
                List<ContentItem> contentItems = (linkItem.Infos != null) ? new List<ContentItem>(linkItem.Infos) : new List<ContentItem>();
                contentItems.RemoveAll(c => c.UniqueId == PhotoPageDetail.UniqueId);
                contentItems.Add(PhotoPageDetail);
                linkItem.Infos = contentItems.OrderBy(c => c.SortOrder).ToArray();
                await _repository.UpsertDocument(linkItem);
                return RedirectToPage("Index", new { permalink = linkItem.UrlTitle });
            }
            else
            {
                ViewData["Message"] = "Da stimmt was nicht.";
                return Page();
            }
        }
    }
}

Pages/Fotos/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;

namespace robert_brands_com.Pages.Fotos
{
    [AllowAnonymous]
    public class IndexModel : LoggedPageModel
    {
        private const string listName = "Fotos";
        private ICosmosDBRepository<CommentedLinkItem> repository;
        public IEnumerable<CommentedLinkItem> CommentedLinks { get; private set; }
        public CommentedLinkItem ReferencedPhotoPage { get; private set; }
        public ContentItem HeaderItem { get; private set; }

        public IndexModel(ICosmosDBRepository<CommentedLinkItem> repositoryService, IActivityLog activityLog) : base(activityLog, "Fotos")
        {
            this.repository = repositoryService;
        }

        public async Task OnGet(string category = null)
        {
            await this.LogGetActivity();
            if (String.IsNullOrEmpty(category))
            {
                IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments(d => d.ListName == listName);
                CommentedLinks = documents.OrderByDescending(d => d.Date);
                if (CommentedLinks.Any())
                {
                    ViewData["Image"] = CommentedLinks.First()?.ImageLink;
                }
            }
            else
            {
                string permaLinkLower = category.ToLower();
                ReferencedPhotoPage = (await repository.GetDocuments(d => d.UrlTitle == permaLinkLower)).OrderByDescending(d => d.Date).FirstOrDefault();
                await this.LogActivity(permaLinkLower);
                if (ReferencedPhotoPage == null)
                {
                    // Now check if a category matches the given argument
                    IEnumerable<CommentedLinkItem> documents = await repository.GetDocuments(d => 
                        d.ListName.Equals(listName, StringComparison.OrdinalIgnoreCase) && 
                        d.Category.Equals(category, StringComparison.OrdinalIgnoreCase));
                    CommentedLinks = documents.OrderByDescending(d => d.Date);
                    if (CommentedLinks.Any())
                    {
                        ViewData["Image"] = CommentedLinks.First()?.ImageLink;
                    }
                }
                else
                {
                    if (ReferencedPhotoPage.Infos != null)
                    {
                        List<ContentItem> infos = new List<ContentItem>(ReferencedPhotoPage.Infos);
                        this.HeaderItem = infos.Find(c => c.SortOrder == 0);
                        infos.ForEach(c => c.ReferenceId = ReferencedPhotoPage.Id);
                    }
                }

            }
        }
        // only on Page level [Authorize(KnownRoles.Admin)]
        public async Task<IActionResult> OnGetDeleteLinkAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            await repository.DeleteDocumentAsync(documentid);
            ViewData["Message"] = "Eintrag gelöscht";

            return RedirectToPage();
        }
        // only on page level [Authorize(KnownRoles.Admin)]
        public async Task<IActionResult> OnGetDeleteContentItemAsync(string documentid, string contentitemid)
        {
            CommentedLinkItem linktItem = await repository.GetDocument(documentid);
            if (linktItem == null)
            {
                return new NotFoundResult();
            }
            if (linktItem.Infos != null)
            {
                List<ContentItem> infos = new List<ContentItem>(linktItem.Infos);
                infos.RemoveAll(c => c.UniqueId == contentitemid);
                linktItem.Infos = infos.ToArray();
                await repository.UpsertDocument(linktItem);
            }
            ViewData["Message"] = "Eintrag gelöscht";

            return RedirectToPage();
        }

    }
}

Pages/Fotos/NewFotoLink.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Fotos
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class NewFotoLinkModel : PageModel
    {
        private ICosmosDBRepository<CommentedLinkItem> repository;
        private ICosmosDBRepository<ListCategory> categoryRepository;
        private IActivityLog activityLog;
        public IEnumerable<CommentedLinkItem> CommentedLinks { get; private set; }
        public IEnumerable<ListCategory> Categories { get; private set; }
        [BindProperty]
        public CommentedLinkItem NewLink { get; set; }
        [BindProperty]
        public bool UserRole { get; set; }

        public NewFotoLinkModel(ICosmosDBRepository<CommentedLinkItem> repositoryService, ICosmosDBRepository<ListCategory> categoryRepository, IActivityLog activityLogRepository)
        {
            this.repository = repositoryService;
            this.categoryRepository = categoryRepository;
            this.activityLog = activityLogRepository;
            this.NewLink = new CommentedLinkItem();
            this.NewLink.ListName = "Fotosammlung";
        }
        public async Task OnGetAsync()
        {
            Categories = await categoryRepository.GetDocuments(d => d.ListName == "Fotos");
        }
        public async Task<IActionResult> OnGetChangeLinkAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            NewLink = await repository.GetDocument(documentid);
            if (null == NewLink)
            {
                return new NotFoundResult();
            }
            Categories = await categoryRepository.GetDocuments(d => d.ListName == "Fotos");
            if (NewLink.Roles != null)
            {
                UserRole = NewLink.Roles.Contains("User");
            }
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                this.NewLink.Author = this.User.Identity.Name;
                List<string> Roles = new List<string>();
                if (UserRole) Roles.Add("User");
                if (Roles.Count > 0) this.NewLink.Roles = Roles.ToArray();
                if (!String.IsNullOrEmpty(NewLink.Id))
                {
                    CommentedLinkItem existingLink = await repository.GetDocument(NewLink.Id);
                    if (null != existingLink)
                    {
                        NewLink.Infos = existingLink.Infos;
                    }
                }
                await this.repository.UpsertDocument(NewLink);
                string targetPage;
                switch (NewLink.ListName)
                {
                    case "Scuderia":
                        targetPage = "/Rad/Scuderia";
                        break;
                    case "Fotos":
                        targetPage = "/Fotos/Index";
                        break;
                    default:
                        targetPage = "./Album";
                        break;
                }
                return RedirectToPage(targetPage);
            }
            else
            {
                Categories = await categoryRepository.GetDocuments(d => d.ListName == "Fotos");
                ViewData["Message"] = "Da stimmt was nicht.";
                return Page();
            }
        }
    }
}

Pages/Fotos/Album.cshtml
@page "{category?}"
@using System.Security.Claims
@model robert_brands_com.Pages.Fotos.AlbumModel
@{
    ViewData["Title"] = "Fotoalbum";
    ViewBag.NoRobots = true;
    ViewBag.Description = "Sammlung der Fotolinks";
}

<div class="container">
    <div class="jumbotron p-3 p-md-5 rounded">
        <h1 class="display-4">Fotoalbum</h1>
        <div class="lead my-3">
            Dies ist eine kleine Linksammlung der Fotos der letzten Zeit. Manchmal ist es bei den ganzen Links zu OneDrive, Flickr, Adobe Lightroom nicht ganz
            leicht, die Übersicht zu bewahren. Da soll diese Seite etwas helfen.
        </div>
        <h4>@ViewData["Message"]</h4>
    </div>
    <div class="album py-5 bg-light">
        <div class="container">
            @if (User.IsInAnyRole(KnownRoles.Admin))
            {
                <div class="row">
                    <div class="col-md-12">
                        <ul class="list-inline">
                            <li class="list-inline-item">Filter</li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Riwa">Riwa</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Reise">Reisen</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Event">Events</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Koeln">Köln</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Wandern">Wandern</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="Rad">Rad</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Album" asp-route-category="">Alle</a></li>
                            <li class="list-inline-item">
                                <form class="form-inline" method="post">
                                    <input class="form-control mr-sm-2" type="search" placeholder="Suchen" aria-label="Suchen" asp-for="Search" />
                                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-page-handler="search">Suchen</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            }
            <div class="row">
                @foreach (robert_brands_com.Models.CommentedLinkItem link in Model.CommentedLinks)
                {
                    @if (User.IsInRole(KnownRoles.Admin) || User.IsInAnyRole(link.Roles))
                    {
                        <div class="col-md-3">
                            <div class="card box-shadow">
                                <a href="@link.Link" target="_blank" title="@link.ShortTitle">
                                    <img class="card-img-top" src="@link.ImageLink" alt="@link.ShortTitle">
                                </a>
                                <div class="card-body">
                                    <div class="card-text">@Html.Raw(link.Description)</div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="@link.Link" target="_blank" title="@link.ShortTitle" class="btn btn-sm btn-outline-secondary">@link.Title</a>
                                            @if (User.IsInRole(KnownRoles.Admin))
                                            {
                                                <a asp-page="/Fotos/NewFotoLink" asp-page-handler="changelink" asp-route-documentid="@link.Id" class="btn btn-sm btn-outline-secondary">
                                                    <span class="fi-pencil" title="Ändern" aria-hidden="true"></span>
                                                </a>
                                                <a asp-page-handler="deletelink" asp-route-documentid="@link.Id" class="btn btn-sm btn-outline-secondary">
                                                    <span class="fi-trash" title="Löschen" aria-hidden="true"></span>
                                                </a>
                                            }
                                        </div>
                                        <small class="text-muted">@link.Date.ToString("dd.MM.yyyy")</small>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">@link.ListName</div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

Pages/Fotos/Index.cshtml
@page "{category?}"
@using System.Security.Claims
@using robert_brands_com.Models
@model robert_brands_com.Pages.Fotos.IndexModel
@{
    ViewData["Title"] = "Fotos";
    if (!String.IsNullOrEmpty(Model.ReferencedPhotoPage?.Title))
    {
        ViewData["Title"] = Model.ReferencedPhotoPage?.Title;
    }
    ViewBag.Description = "Eine Sammlung meiner Fotos auf Flickr, OneDrive und Adobe Lightroom.";
    ViewBag.Keywords = "Fotografie,Reise,Köln";
    if (!String.IsNullOrEmpty(Model.ReferencedPhotoPage?.PlainDescription))
    {
        ViewData["Description"] = Model.ReferencedPhotoPage?.PlainDescription;
    }
    if (!String.IsNullOrEmpty(Model.ReferencedPhotoPage?.ImageLink))
    {
        ViewBag.Image = Model.ReferencedPhotoPage?.ImageLink;
    }
}
<div class="container">
    @if (Model.ReferencedPhotoPage == null)
    {
        <div class="jumbotron p-3 p-md-5 rounded">
            <h1 class="display-4">Fotoalbum</h1>
            <p class="lead my-3">
                Meistens habe ich eine Kamera dabei... Die Fotos landen bei Flickr, OneDrive, Adobe Lightroom. Manchmal verliere ich da selbst die Übersicht - deswegen sammel ich
                hier die Links zu einigen der Fotos.
            </p>
            <h4>@ViewData["Message"]</h4>
        </div>
        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="list-inline">
                            <li class="list-inline-item">Filter</li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="Reise">Reisen</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="Koeln">Köln</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="Rad">Rad</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="Whippetlove">Whippetlove</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="Event">Events</a></li>
                            <li class="list-inline-item"><a asp-page="/Fotos/Index" asp-route-category="">Alle</a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    @foreach (robert_brands_com.Models.CommentedLinkItem link in Model.CommentedLinks)
                    {
                        <div class="col-md-6">
                            <div class="card box-shadow">
                                <a href="@link.Link" target="_blank" title="@link.ShortTitle">
                                    <img class="card-img-top" src="@link.ImageLink" alt="@link.ShortTitle">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title">@link.Title</h5>
                                    <div class="card-text">
                                        @Html.Raw(link.Description)
                                        @if (!String.IsNullOrEmpty(link.UrlTitle))
                                        {
                                            <p><a asp-route-category="@link.UrlTitle">Mehr ...</a></p>
                                        }
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="@link.Link" target="_blank" title="@link.ShortTitle" class="btn btn-sm btn-outline-secondary">@link.ShortTitle</a>
                                            @if (User.IsInRole(KnownRoles.Admin))
                                            {
                                                <a asp-page="/Fotos/NewFotoLink" asp-page-handler="changelink" asp-route-documentid="@link.Id" class="btn btn-sm btn-outline-secondary">
                                                    <span class="fi-pencil" title="Ändern" aria-hidden="true"></span>
                                                </a>
                                                <a asp-page-handler="deletelink" asp-route-documentid="@link.Id" class="btn btn-sm btn-outline-secondary">
                                                    <span class="fi-trash" title="Löschen" aria-hidden="true"></span>
                                                </a>
                                            }
                                        </div>
                                        <small class="text-muted">@link.Date.ToString("dd.MM.yyyy")</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
    else
    {
        @if (Model.HeaderItem != null)
        {
            @if (!String.IsNullOrEmpty(Model.HeaderItem.EmbeddedLink))
            {
                <div class="row">
                    <div class="col">
                        <div class="card">
                            @if (Model.HeaderItem.ContentType == ContentType.FlickrWithHeader)
                            {
                                <a target="_blank" data-flickr-embed="true" data-header="true" data-footer="false" href="@Model.HeaderItem.EmbeddedLink" title="@Model.HeaderItem.Title"><img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" alt="@Model.HeaderItem.Title"></a>
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.Flickr)
                            {
                                <a target="_blank" data-flickr-embed="true" data-header="false" data-footer="false" href="@Model.HeaderItem.EmbeddedLink" title="@Model.HeaderItem.Title"><img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" alt="@Model.HeaderItem.Title"></a>
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.FlickrWithFooter)
                            {
                                <a target="_blank" data-flickr-embed="true" data-header="false" data-footer="true" href="@Model.HeaderItem.EmbeddedLink" title="@Model.HeaderItem.Title"><img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" alt="@Model.HeaderItem.Title"></a>
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.FlickrWithHeaderAndFooter)
                            {
                                <a target="_blank" data-flickr-embed="true" data-header="true" data-footer="true" href="@Model.HeaderItem.EmbeddedLink" title="@Model.HeaderItem.Title"><img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" alt="@Model.HeaderItem.Title"></a>
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.EmbeddedLink)
                            {
                                <a href="@Model.HeaderItem.EmbeddedLink" target="_blank" title="@Model.HeaderItem.Header"><img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" /></a>
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.Text)
                            {
                                <img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" />
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.Text)
                            {
                                <img class="img-fluid card-img-top" src="@Model.HeaderItem.ImageLink" />
                            }
                            else if (Model.HeaderItem.ContentType == ContentType.Strava || Model.HeaderItem.ContentType == ContentType.Gpsies || Model.HeaderItem.ContentType == ContentType.Lightroom)
                            {
                                <div class="embed-responsive embed-responsive-4by3">
                                    <iframe class="embed-responsive-item" src='@Model.HeaderItem.EmbeddedLink'></iframe>
                                </div>
                            }
                            @if (!String.IsNullOrEmpty(Model.HeaderItem.Description))
                            {
                                <div class="card-body">
                                    <p class="card-text">
                                        @Html.Raw(Model.HeaderItem.Description)
                                    </p>
                                    @if (!String.IsNullOrEmpty(Model.HeaderItem.Link))
                                    {
                                        <a href="@Model.HeaderItem.Link" target="_blank" title="@Model.HeaderItem.LinkTitle" class="btn btn-primary">@Model.HeaderItem.LinkTitle</a>

                                    }
                                </div>

                            }
                        </div>
                    </div>
                </div>
            }
        }
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-8">
                    <h1>@Model.ReferencedPhotoPage.Title</h1>
                    <div>
                        @Html.Raw(Model.ReferencedPhotoPage.Description)
                        @Html.Raw(Model.ReferencedPhotoPage.LongDescription)
                    </div>
                    @if (User.IsInRole(KnownRoles.Admin))
                    {
                        <a asp-page="/Fotos/NewFotoLink" asp-page-handler="changelink" asp-route-documentid="@Model.ReferencedPhotoPage.Id" class="btn btn-sm btn-outline-secondary">
                            <span class="fi-pencil" title="Ändern" aria-hidden="true"></span>
                        </a>
                        <a asp-page="/Fotos/EditContentItem" asp-route-documentid="@Model.ReferencedPhotoPage.Id" class="btn btn-sm btn-outline-secondary">
                            Neue Info
                        </a>
                    }
                </div>
                <div class="col">
                    @if (!String.IsNullOrEmpty(Model.ReferencedPhotoPage.ImageLink))
                    {
                        <img class="img-fluid" src="@Model.ReferencedPhotoPage.ImageLink" alt="@Model.ReferencedPhotoPage.Title">
                    }
                </div>
            </div>
        </div>
        <div class="row">
            @if (null != Model.ReferencedPhotoPage.Infos)
            {
                @foreach (ContentItem infoBlock in Model.ReferencedPhotoPage.Infos)
                {
                    @if (infoBlock.SortOrder != 0 || User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
                    {
                        <div class="col-md-@infoBlock.ColumnWidth">
                            @{
                                await Html.RenderPartialAsync("_ContentItem", infoBlock);
                            }
                        </div>
                    }
                }
            }
        </div>
        @section Metatags {
            <meta property="og:type" content="article" />
        }

    }
</div>
@section Scripts {
    <script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
    <script src="https://player.vimeo.com/api/player.js"></script>
}