Controllers/CalendarController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;
using System.Globalization;
using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;


namespace robert_brands_com.Controllers
{
    public class CalendarController : Controller
    {
        private ICosmosDBRepository<CalendarItem> repository;
        public CalendarController(ICosmosDBRepository<CalendarItem> repositoryService)
        {
            this.repository = repositoryService;
        }
        [Authorize(Policy = KnownRoles.PolicyIsCalendarCoordinator)]
        public async Task<FileContentResult> ExportRegistrationsAsCSV(string id)
        {
            CalendarItem calendarItem = await repository.GetDocument(id);
            IEnumerable<Member> registratedMembers = calendarItem.Members;
            StringWriter csvData = new StringWriter();
            csvData.WriteLine("{0};{1};{2};{3};{4}", "Name", "E-Mail", "Participants", "Registration date", "Remark");
            foreach (Member m in registratedMembers)
            {
                csvData.WriteLine("{0};{1};{2};{3};{4}", m.Name, m.EMail, m.Count, m.RegistrationDate, m.Remark);
            }
            DateTime dateForFilename = calendarItem.StartDate;
            string fileName = String.Format("{0:yyyy}-{1:MM}-{2:dd}{3}.csv", dateForFilename, dateForFilename, dateForFilename, calendarItem.Title);
            return File(new System.Text.UTF8Encoding().GetBytes(csvData.ToString()), "text/csv", fileName);
        }
        [AllowAnonymous]
        public async Task<IActionResult> ExportICal(string calendarItemId)
        {
            CalendarItem calendarItem = await repository.GetDocument(calendarItemId);
            if (calendarItem == null)
            {
                return new NotFoundResult();
            }
            string description = calendarItem.PlainDescription ?? calendarItem.Summary ?? String.Empty;
            if (!String.IsNullOrEmpty(calendarItem.UrlTitle))
            {
                description += " https://robert-brands.com/termine/" + calendarItem.UrlTitle;
            }
            CalendarEvent e = new CalendarEvent
            {
                Start = new CalDateTime(calendarItem.StartDate),
                End = new CalDateTime(calendarItem.EndDate),
                Summary = calendarItem.Title,
                Description = description,
                Location = calendarItem.Place,
                IsAllDay = calendarItem.WholeDay,
                Organizer = new Organizer(calendarItem.Host)
            };
            Ical.Net.Calendar calendar = new Ical.Net.Calendar();
            calendar.Events.Add(e);

            var serializer = new Ical.Net.Serialization.CalendarSerializer();
            string iCal = serializer.SerializeToString(calendar);
            return File(new System.Text.UTF8Encoding().GetBytes(iCal), "text/calendar", "iCal.ics");
        }
    }
}

Pages/Termine/AdminRegistration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Termine
{
    [Authorize(Policy = KnownRoles.PolicyIsCalendarCoordinator)]
    public class AdminRegistrationModel : PageModel
    {
        private ICosmosDBRepository<CalendarItem> _calendarRepository;
        public CalendarItem ReferencedCalenderItem { get; private set; }
        public List<Member> RegisteredUsers { get; private set; } = new List<Member>();
        public List<RegistrationKey> RegistrationKeys { get; private set; } = new List<RegistrationKey>();
        [BindProperty]
        public RegistrationKey NewRegistrationKey { get; set; }
        [BindProperty]
        public string CalendarItemId { get; set; }
        public AdminRegistrationModel(ICosmosDBRepository<CalendarItem> calendarRepository)
        {
            _calendarRepository = calendarRepository;
        }

        public async Task<IActionResult> OnGetAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            ReferencedCalenderItem = await _calendarRepository.GetDocument(documentid);
            CalendarItemId = ReferencedCalenderItem.Id;
            if (ReferencedCalenderItem == null)
            {
                return new NotFoundResult();
            }
            if (ReferencedCalenderItem.Members != null)
            {
                RegisteredUsers.AddRange(ReferencedCalenderItem.Members);
            }
            if (ReferencedCalenderItem.RegistrationKeys != null)
            {
                RegistrationKeys.AddRange(ReferencedCalenderItem.RegistrationKeys);
            }
            Random randomGen = new Random();
            NewRegistrationKey = new RegistrationKey { UniqueId = Guid.NewGuid().ToString(), Key = randomGen.Next(1000, 1000000).ToString() };
            return Page();
        }
        public async Task<IActionResult> OnPostAddRegistrationKeyAsync()
        {
            ReferencedCalenderItem = await _calendarRepository.GetDocument(CalendarItemId);
            if (null == ReferencedCalenderItem)
            {
                return new NotFoundResult();
            }
            if (ModelState.IsValid)
            {
                List<RegistrationKey> members = (ReferencedCalenderItem.RegistrationKeys != null) ? new List<RegistrationKey>(ReferencedCalenderItem.RegistrationKeys) : new List<RegistrationKey>();
                members.RemoveAll(c => c.Key == NewRegistrationKey.Key);
                members.Add(NewRegistrationKey);
                ReferencedCalenderItem.RegistrationKeys = members.ToArray();
                await _calendarRepository.UpsertDocument(ReferencedCalenderItem);
                return RedirectToPage(new { documentid = CalendarItemId });
            }
            else
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
        }

        public async Task<IActionResult> OnGetDeleteAsync(string documentid, string memberid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            ReferencedCalenderItem = await _calendarRepository.GetDocument(documentid);
            if (ReferencedCalenderItem == null || ReferencedCalenderItem.Members == null)
            {
                return new NotFoundResult();
            }
            RegisteredUsers.AddRange(ReferencedCalenderItem.Members);
            RegisteredUsers.RemoveAll(m => m.UniqueId == memberid);
            ReferencedCalenderItem.Members = RegisteredUsers.ToArray();
            await _calendarRepository.UpsertDocument(ReferencedCalenderItem);
            return RedirectToPage(new { documentid = ReferencedCalenderItem.Id });
        }
        public async Task<IActionResult> OnGetDeleteRegistrationKeyAsync(string documentid, string registrationkeyid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            ReferencedCalenderItem = await _calendarRepository.GetDocument(documentid);
            if (ReferencedCalenderItem == null || ReferencedCalenderItem.RegistrationKeys == null)
            {
                return new NotFoundResult();
            }
            RegistrationKeys.AddRange(ReferencedCalenderItem.RegistrationKeys);
            RegistrationKeys.RemoveAll(m => m.UniqueId == registrationkeyid);
            ReferencedCalenderItem.RegistrationKeys = RegistrationKeys.ToArray();
            await _calendarRepository.UpsertDocument(ReferencedCalenderItem);
            return RedirectToPage(new { documentid = ReferencedCalenderItem.Id });
        }
    }
}

Pages/Termine/Anmelden.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using reCAPTCHA.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;


namespace robert_brands_com.Pages.Termine
{
    [AllowAnonymous]
    public class AnmeldenModel : PageModel
    {
        private IRecaptchaService _recaptcha;
        private ICosmosDBRepository<CalendarItem> _repository;
        [BindProperty]
        public string CalendarItemId { get; set; }
        [BindProperty]
        public Member NewMember { get; set; }
        public CalendarItem ReferencedCalendarItem { get; set; }
        public bool UseCaptcha { get; private set; } = true;

        public AnmeldenModel(ICosmosDBRepository<CalendarItem> calendarRepository, IRecaptchaService recaptcha)
        {
            _repository = calendarRepository;
            _recaptcha = recaptcha;
        }
        public async Task<IActionResult> OnGetCheckInOutAsync(string documentid)
        {
            if (String.IsNullOrEmpty(documentid))
            {
                return new NotFoundResult();
            }
            CalendarItemId = documentid;
            ReferencedCalendarItem = await _repository.GetDocument(documentid);
            UseCaptcha = !User.Identity.IsAuthenticated && ReferencedCalendarItem.PublicListing;
            if (null == ReferencedCalendarItem || !ReferencedCalendarItem.RegistrationOpen && !User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
            {
                return new NotFoundResult();
            }
            List<Member> members = (ReferencedCalendarItem.Members != null) ? new List<Member>(ReferencedCalendarItem.Members) : new List<Member>();
            NewMember = new Member { UniqueId = Guid.NewGuid().ToString(), RegistrationDate = DateTime.UtcNow, Count = 1 };

            return Page();
        }
        public async Task<IActionResult> OnGetAsync(string permalink = null, string registrationkey = null)
        {
            if (String.IsNullOrEmpty(permalink))
            {
                return new NotFoundResult();
            }
            string permaLinkLower = permalink.ToLower();
            ReferencedCalendarItem = (await _repository.GetDocuments(d => d.UrlTitle == permaLinkLower)).OrderByDescending(d => d.StartDate).FirstOrDefault();
            if (null == ReferencedCalendarItem || !ReferencedCalendarItem.RegistrationOpen && !User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
            {
                return new NotFoundResult();
            }
            CalendarItemId = ReferencedCalendarItem.Id;
            UseCaptcha = !User.Identity.IsAuthenticated && ReferencedCalendarItem.PublicListing;
            List<Member> members = (ReferencedCalendarItem.Members != null) ? new List<Member>(ReferencedCalendarItem.Members) : new List<Member>();
            NewMember = new Member { UniqueId = Guid.NewGuid().ToString(), RegistrationDate = DateTime.UtcNow, Count = 1, RegistrationKey = registrationkey };

            return Page();
        }
        // only on page level [Authorize(Policy = KnownRoles.PolicyIsCalendarCoordinator)]
        public async Task<IActionResult> OnGetChangeAsync(string documentid, string registrationid)
        {
            if (String.IsNullOrEmpty(documentid) || String.IsNullOrEmpty(registrationid))
            {
                return new NotFoundResult();
            }
            CalendarItemId = documentid;
            ReferencedCalendarItem = await _repository.GetDocument(documentid);
            if (null == ReferencedCalendarItem)
            {
                return new NotFoundResult();
            }
            UseCaptcha = !User.Identity.IsAuthenticated && !ReferencedCalendarItem.PublicListing;
            List<Member> members = (ReferencedCalendarItem.Members != null) ? new List<Member>(ReferencedCalendarItem.Members) : new List<Member>();
            if (null == ReferencedCalendarItem.Members)
            {
                return new NotFoundResult();
            }
            NewMember = members.Find(c => c.UniqueId == registrationid);
            if (null == NewMember)
            {
                return new NotFoundResult();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostUnregisterAsync()
        {
            ReferencedCalendarItem = await _repository.GetDocument(CalendarItemId);
            UseCaptcha = !User.Identity.IsAuthenticated && null != ReferencedCalendarItem && ReferencedCalendarItem.PublicListing;
            if (UseCaptcha)
            {
                RecaptchaResponse captchaValid = await _recaptcha.Validate(Request);
                if (!captchaValid.success)
                {
                    ModelState.AddModelError("reCaptcha", "Bitte das reCaptcha bestätigen.");
                }
            }
            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
            Member memberToUnregister;
            List<Member> members;
            if (null == ReferencedCalendarItem)
            {
                return new NotFoundResult();
            }
            members = (ReferencedCalendarItem.Members != null) ? new List<Member>(ReferencedCalendarItem.Members) : new List<Member>();
            memberToUnregister = members.Find(m => m.EMail == NewMember.EMail && m.Name == NewMember.Name);
            if (null == memberToUnregister)
            {
                ModelState.AddModelError("EMail", "E-Mail und Name stimmen mit keiner Anmeldung überein.");
                return Page();
            }
            if (ReferencedCalendarItem.RegistrationKeyRequired)
            {
                RegistrationKey checkKey = ReferencedCalendarItem.RegistrationKeys.FirstOrDefault(r => r.Key == NewMember.RegistrationKey);
                if (null == checkKey)
                {
                    ModelState.AddModelError("RegistrationKey", "Der angegebene Registrierungsschlüssel ist nicht zulässig.");
                    return Page();
                }
            }
            if (ModelState.IsValid)
            {
                members.RemoveAll(c => c.UniqueId == memberToUnregister.UniqueId);
                ReferencedCalendarItem.Members = members.OrderBy(m => m.RegistrationDate).ToArray();
                await _repository.UpsertDocument(ReferencedCalendarItem);
                ViewData["Message"] = "Abgemeldet";
                return RedirectToPage("Index", new { permalink = ReferencedCalendarItem.UrlTitle, message = "Anmeldung gelöscht." });
            }
            else
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
        }
        public async Task<IActionResult> OnPostAsync()
        {
            ReferencedCalendarItem = await _repository.GetDocument(CalendarItemId);
            UseCaptcha = !User.Identity.IsAuthenticated && null != ReferencedCalendarItem && ReferencedCalendarItem.PublicListing;
            if (UseCaptcha)
            {
                RecaptchaResponse captchaValid = await _recaptcha.Validate(Request, false);
                if (!captchaValid.success)
                {
                    ModelState.AddModelError("reCaptcha", "Bitte das reCaptcha bestätigen.");
                }
            }
            if (ModelState.IsValid)
            {
                if (null == ReferencedCalendarItem)
                {
                    return new NotFoundResult();
                }
                if (ReferencedCalendarItem.RegistrationKeyRequired && !User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
                {
                    RegistrationKey checkKey = ReferencedCalendarItem.RegistrationKeys.FirstOrDefault(r => r.Key == NewMember.RegistrationKey);
                    if (null == checkKey)
                    {
                        ModelState.AddModelError("RegistrationKey", "Der angegebene Registrierungsschlüssel ist nicht zulässig.");
                        return Page();
                    }
                }
                List<Member> members = (ReferencedCalendarItem.Members != null) ? new List<Member>(ReferencedCalendarItem.Members) : new List<Member>();
                members.RemoveAll(c => c.UniqueId == NewMember.UniqueId);
                members.Add(NewMember);
                ReferencedCalendarItem.Members = members.OrderBy(m => m.RegistrationDate).ToArray();
                if (ReferencedCalendarItem.GetRegisteredMembersCount() > ReferencedCalendarItem.MaxRegistrationsCount && !User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
                {
                    ModelState.AddModelError("RegistrationCount", "Die Anzahl Anmeldungen überschreitet die maximale Teilnehmeranzahl.");
                    return Page();
                }
                await _repository.UpsertDocument(ReferencedCalendarItem);
                return RedirectToPage("Index", new { permalink = ReferencedCalendarItem.UrlTitle, message = "Anmeldung erfolgt." });
            }
            else
            {
                return Page();
            }
        }
    }
}

Pages/Termine/AdminRegistration.cshtml
@page
@using System.Security.Claims
@using robert_brands_com.Models
@model robert_brands_com.Pages.Termine.AdminRegistrationModel
@using Microsoft.Extensions.Options;
@inject IOptions<robert_brands_com.Repositories.TinyMCEConfig> TinyMCEConfig
@{
    ViewData["Title"] = "Verwaltung der Registrierungen";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h4>@ViewData["Title"]</h4>
            <h5>@ViewData["Message"]</h5>
        </div>
        <div class="card-body">
            <div class="card-text">
                <h3 class="card-title">@Model.ReferencedCalenderItem.Title</h3>
                <p>
                    Verwaltung der Anmeldungen. Aktuell @Model.ReferencedCalenderItem.GetRegisteredMembersCount()/@Model.ReferencedCalenderItem.MaxRegistrationsCount Personen angemeldet.
                </p>
                <a asp-page="Anmelden" asp-route-permalink="@Model.ReferencedCalenderItem.UrlTitle" title="Registration-Link">Registration-Link</a>
                <a class="btn btn-primary" asp-controller="Calendar" asp-route-id="@Model.ReferencedCalenderItem.Id" asp-action="ExportRegistrationsAsCSV">Export CSV</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Registration Keys</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-sm table-bordered table-hover table-striped">
                            <tbody class="font-weight-light">
                                @foreach (RegistrationKey key in Model.RegistrationKeys)
                                {
                                    <tr>
                                        <td>@key.Key</td>
                                        <td>@key.Description</td>
                                        <td>
                                            <a asp-page-handler="deleteregistrationkey" asp-route-documentid="@Model.ReferencedCalenderItem.Id" asp-route-registrationkeyid="@key.UniqueId" class="btn btn-sm btn-outline-secondary">
                                                <span class="fi-trash" title="Löschen" aria-hidden="true"></span>
                                            </a>
                                        </td>
                                        <td>
                                            <a asp-page="Anmelden" asp-route-permalink="@Model.ReferencedCalenderItem.UrlTitle" asp-route-registrationkey="@key.Key">Link</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <form method="post">
                        <div asp-validation-summary="All" class="bg-warning"></div>
                        <input asp-for="CalendarItemId" type="hidden" />
                        <input asp-for="NewRegistrationKey.UniqueId" type="hidden" />
                        <div class="form-group">
                            <label asp-for="NewRegistrationKey.Key"></label>
                            <input class="form-control" asp-for="NewRegistrationKey.Key" />
                        </div>
                        <div class="form-group">
                            <label asp-for="NewRegistrationKey.Description"></label>
                            <input class="form-control" asp-for="NewRegistrationKey.Description" />
                        </div>
                        <div class="btn-group">
                            <button class="btn btn-primary" asp-page-handler="addregistrationkey" type="submit" asp->Speichern</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        @foreach (Member member in Model.RegisteredUsers)
        {
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        @member.Name
                    </div>
                    <div class="card-body">
                        <div class="card-text">
                            <dl>
                                <dt>E-Mail</dt>
                                <dd>@member.EMail</dd>
                                <dt>Anzahl</dt>
                                <dd>@member.Count</dd>
                                <dt>Anmeldedatum</dt>
                                <dd>@member.RegistrationDate.ToString("yyyy-MM-dd HH:mm")</dd>
                                @if (!String.IsNullOrEmpty(member.Remark))
                                {
                                    <dt>Anmerkung</dt>
                                    <dd>@member.Remark</dd>
                                }
                                @if (!String.IsNullOrEmpty(member.RegistrationKey))
                                {
                                    <dt>Registration-Key</dt>
                                    <dd>@member.RegistrationKey</dd>
                                }
                            </dl>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @if (User.IsInAnyRole(KnownRoles.CalendarCoordinatorRoles))
                                    {
                                        <a asp-page="Anmelden" asp-page-handler="change" asp-route-documentid="@Model.ReferencedCalenderItem.Id" asp-route-registrationid="@member.UniqueId" class="btn btn-sm btn-outline-secondary">
                                            <span class="fi-pencil" title="Ändern" aria-hidden="true"></span>
                                        </a>
                                        <a asp-page-handler="delete" asp-route-documentid="@Model.ReferencedCalenderItem.Id" asp-route-memberid="@member.UniqueId" class="btn btn-sm btn-outline-secondary">
                                            <span class="fi-trash" title="Löschen" aria-hidden="true"></span>
                                        </a>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts {
    <script src="https://cdn.tiny.cloud/1/@TinyMCEConfig.Value.ApiKey/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker searchreplace wordcount visualblocks visualchars code insertdatetime media nonbreaking save table directionality emoticons template paste',
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons'
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Termine/Anmelden.cshtml
@page "{permalink?}/{registrationkey?}"
@model robert_brands_com.Pages.Termine.AnmeldenModel
@using robert_brands_com.Models
@using Microsoft.Extensions.Options
@using reCAPTCHA.AspNetCore
@inject IOptions<RecaptchaSettings> RecaptchaSettings
@inject IOptions<robert_brands_com.Repositories.TinyMCEConfig> TinyMCEConfig
@{
    ViewData["Title"] = "Für Veranstaltung anmelden";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h4>@ViewData["Title"]</h4>
            <h5>@ViewData["Message"]</h5>
        </div>
        <div class="card-body">
            <div class="card-text">
                <h3 class="card-title">@Model.ReferencedCalendarItem.Title</h3>
                <h6>@Model.ReferencedCalendarItem.GetEventDateAsString()</h6>
                @if (String.IsNullOrEmpty(Model.ReferencedCalendarItem.RegistrationDescription))
                {
                    <text>
                        Hier erfolgt die An- und auch Abmeldung. Für eine Abmeldung bitte den Namen und die E-Mail-Adresse genau wie bei der Anmeldung eingeben.
                        @if (Model.ReferencedCalendarItem.RegistrationKeyRequired)
                        {
                            <text>Auch der Registrierungsschlüssel muss für eine Abmeldung wieder eingegeben werden.</text>
                }
                        E-Mail und Telefonnummmer wird ggf. nur für Benachrichtigungen rund um diesen Termin verwendet und nicht für eine weitere Verwendung gespeichert.
                        </text>
                    }
                    else
                    {
                        @Html.Raw(Model.ReferencedCalendarItem.RegistrationDescription)
                    }
            </div>
            <form method="post">
                <div asp-validation-summary="All" class="bg-warning"></div>
                <input asp-for="CalendarItemId" type="hidden" />
                <input asp-for="NewMember.UniqueId" type="hidden" />
                <input asp-for="NewMember.RegistrationDate" type="hidden" />
                @if (Model.ReferencedCalendarItem.RegistrationKeyRequired)
                {
                    <div class="form-group">
                        <label asp-for="NewMember.RegistrationKey"></label>
                        <input class="form-control" asp-for="NewMember.RegistrationKey" />
                    </div>
                }
                <div class="form-group">
                    <label asp-for="NewMember.Name"></label>
                    <input class="form-control" asp-for="NewMember.Name" />
                </div>
                <div class="form-group">
                    <label asp-for="NewMember.EMail"></label>
                    <input class="form-control" asp-for="NewMember.EMail" />
                </div>
                @if (Model.ReferencedCalendarItem.AllowFriends)
                {
                    <div class="form-group">
                        <label asp-for="NewMember.Count"></label>
                        <input class="form-control" asp-for="NewMember.Count" />
                    </div>
                }
                else
                {
                    <input asp-for="NewMember.Count" type="hidden" />
                }
                <div class="form-group">
                    <label asp-for="NewMember.Remark"></label>
                    <input class="form-control" asp-for="NewMember.Remark" />
                </div>
                @if (Model.UseCaptcha)
                {
                    <div class="g-recaptcha" data-sitekey="@RecaptchaSettings.Value.SiteKey"></div>
                }

                <p></p>
                <div class="btn-group">
                    <button class="btn btn-primary" type="submit">Anmelden</button>
                    <button class="btn btn-outline-primary" asp-page-handler="Unregister" type="submit">Abmelden</button>
                    <a asp-page="Index" class="btn btn-outline-secondary">Abbrechen</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://cdn.tiny.cloud/1/@TinyMCEConfig.Value.ApiKey/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker searchreplace wordcount visualblocks visualchars code insertdatetime media nonbreaking save table directionality emoticons template paste',
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons'
        });
    </script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}