Models/Shortcut.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace robert_brands_com.Models
{
    public class Shortcut : DocumentDBEntity
    {
        [JsonProperty(PropertyName = "category", NullValueHandling = NullValueHandling.Ignore)]
        [Required(ErrorMessage = "Bitte eine Link-Kategorie angeben")]
        [MaxLength(30, ErrorMessage = "Die Kategorie darf nicht länger als 30 Zeichen sein.")]
        public string Category { get; set; }

        [JsonProperty(PropertyName = "nickname", NullValueHandling = NullValueHandling.Ignore)]
        [Required(ErrorMessage = "Bitte einen Link-Kürzel angeben")]
        [MaxLength(40, ErrorMessage = "Das Kürzel darf nicht länger als 40 Zeichen sein.")]
        public string Nickname { get; set; }

        [JsonProperty(PropertyName = "url", NullValueHandling = NullValueHandling.Ignore)]
        [Required(ErrorMessage = "Bitte eine URL eingeben")]
        [MaxLength(255, ErrorMessage = "Der Shortcut darf nicht länger als 255 Zeichen sein.")]
        public string Url { get; set; }

        [JsonProperty(PropertyName = "remark", NullValueHandling = NullValueHandling.Ignore)]
        [MaxLength(512, ErrorMessage = "Die Bermerkung darf nicht länger als 512 Zeichen sein.")]
        public string Remark { get; set; }
    }
}

Controllers/ShortcutsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;
using robert_brands_com.Pages.Blog;

namespace robert_brands_com.Controllers
{
    public class ShortcutsController : Controller
    {
        private ICosmosDBRepository<Shortcut> repository;

        public ShortcutsController(ICosmosDBRepository<Shortcut> repositoryService)
        {
            this.repository = repositoryService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Link(string category, string nickname)
        {
            Shortcut target = (await repository.GetDocuments(s => s.Category == category && s.Nickname == nickname)).FirstOrDefault();
            if (null != target)
            {
                return this.Redirect(target.Url);
            }
            else
            {   
                // Redirect to Blog/Artikel page if no shortcut found. That page will handle the 404 error. 
                // This redirect makes it possible to use the title of a blog article (nicknam) as a direct link without any configuration
                return RedirectToPage("/Blog/Artikel", new { permalink = nickname });
            }
        }

        [Authorize(Roles = KnownRoles.Admin)]
        public async Task<FileContentResult> ExportShortcutsAsCSV()
        {
            IEnumerable<Shortcut> shortcuts = await repository.GetDocuments();
            StringWriter csvData = new StringWriter();
            csvData.WriteLine("{0};{1};{2};{3}", "Category", "Nickname", "Url", "Remark");
            foreach (Shortcut shortcut in shortcuts)
            {
                csvData.WriteLine("{0};{1};{2};{3}", shortcut.Category, shortcut.Nickname, shortcut.Url, shortcut.Remark);
            }
            DateTime dateForFilename = DateTime.UtcNow;
            string fileName = String.Format("{0:yyyy}-{1:MM}-{2:dd}Shortcuts.csv", dateForFilename, dateForFilename, dateForFilename);
            return File(new System.Text.UTF8Encoding().GetBytes(csvData.ToString()), "text/csv", fileName);
        }

    }
}

Pages/Shortcuts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;

namespace robert_brands_com.Pages.Shortcuts
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class IndexModel : PageModel
    {
        private ICosmosDBRepository<Shortcut> repository;
        public IEnumerable<Shortcut> Shortcuts { get; private set; }

        public IndexModel(ICosmosDBRepository<Shortcut> repositoryService)
        {
            repository = repositoryService;
        }
        public async Task OnGet()
        {
            Shortcuts = await repository.GetDocuments();
        }
        public async Task<IActionResult> OnGetDeleteAsync(string category, string nickname)
        {
            Shortcut shortcut = (await repository.GetDocuments(s => s.Category == category && s.Nickname == nickname)).FirstOrDefault();
            if (null != shortcut)
            {
                await repository.DeleteDocumentAsync(shortcut.Id);
            }
            ViewData["Message"] = "Eintrag gelöscht";
            return RedirectToPage();
        }
    }
}

Pages/Shortcuts/New.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using robert_brands_com.Models;
using robert_brands_com.Repositories;

namespace robert_brands_com.Pages.Shortcuts
{
    [Authorize(Roles = KnownRoles.Admin)]
    public class NewModel : PageModel
    {
        private ICosmosDBRepository<Shortcut> repository;
        [BindProperty]
        public Shortcut NewShortcut { get; set; }

        public NewModel(ICosmosDBRepository<Shortcut> repositoryService)
        {
            repository = repositoryService;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                IEnumerable<Shortcut> list = await repository.GetDocuments(s => s.Category == NewShortcut.Category && s.Nickname == NewShortcut.Nickname);
                Shortcut existingOne = list.FirstOrDefault();
                if (null != existingOne)
                {
                    NewShortcut.Id = existingOne.Id;
                }
                await repository.UpsertDocument(NewShortcut);
                ViewData["Message"] = "Shortcut gespeichert.";
                return RedirectToPage("./Index");
            }
            else
            {
                ViewData["Message"] = "Schiefgegangen";
                return Page();
            }
        }
        public async Task<IActionResult> OnGetChangeShortcutAsync(string category, string nickname)
        {

            IEnumerable<Shortcut> list = await repository.GetDocuments(s => s.Category == category && s.Nickname == nickname);
            NewShortcut = list.FirstOrDefault();
            return Page();
        }

    }
}

Pages/Shortcuts/Index.cshtml
@page
@model robert_brands_com.Pages.Shortcuts.IndexModel
@{
    ViewData["Title"] = "Alle Shortcuts";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-condensed table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Aktionen</th>
                            <th>Kategorie</th>
                            <th>Nickname</th>
                            <th>URL</th>
                            <th>Geändert</th>
                            <th>Bemerkung</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (robert_brands_com.Models.Shortcut s in Model.Shortcuts)
                        {

                            <tr>
                                <td>
                                    <a class="btn btn-outline-dark" asp-page="./New" asp-page-handler="changeshortcut" asp-route-category="@s.Category" asp-route-nickname="@s.Nickname">Ändern</a>
                                    <a class="btn btn-outline-dark" asp-page-handler="delete" asp-route-category="@s.Category" asp-route-nickname="@s.Nickname">Löschen</a>
                                </td>
                                <td>@s.Category</td>
                                <td>@s.Nickname</td>
                                <td><a href="@s.Url" target="_blank" title="@s.Remark">@((s.Url.Length > 30) ? s.Url.Substring(0, 30) : s.Url) </a></td>
                                <td>@s.Remark</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div>
                <a class="btn btn-primary" asp-controller="Shortcuts" asp-action="ExportShortcutsAsCSV">Export CSV</a>
                <a class="btn btn-primary" asp-page="New">Neuer Shortcut</a>
            </div>
        </div>
    </div>
</div>

Pages/Shortcuts/New.cshtml
@page
@model robert_brands_com.Pages.Shortcuts.NewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Neuer Shortcut";
}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>@ViewData["Title"]</h2>
            <h4>@ViewData["Message"]</h4>
        </div>
        <div class="card-body">
            <form method="post">
                <div asp-validation-summary="All" class="bg-warning"></div>
                <div class="form-group">
                    <label asp-for="NewShortcut.Nickname">Link-Kürzel:</label>
                    <input class="form-control" asp-for="NewShortcut.Nickname" />
                </div>
                <div class="form-group">
                    <label asp-for="NewShortcut.Url">Link:</label>
                    <input class="form-control" asp-for="NewShortcut.Url" inputmode="url" />
                </div>
                <div class="form-group">
                    <label asp-for="NewShortcut.Category">Kategorie:</label>
                    <input class="form-control" asp-for="NewShortcut.Category" value="Default" />
                </div>
                <div class="form-group">
                    <label asp-for="NewShortcut.Remark">Bemerkung:</label>
                    <input class="form-control" asp-for="NewShortcut.Remark" />
                </div>
                <button class="btn btn-primary" type="submit">Speichern</button>
            </form>
        </div>
    </div>
</div>